config/routes.rb
Sns::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    match 'contact' => 'contact#create', as: 'contact', via: :post
    
    resources :projects
    resources :project_images
    root to: 'home#index'
  end

  match "*path", to: redirect("/#{I18n.default_locale}/%{path}")
  match "", to: redirect("/#{I18n.default_locale}")

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_images

  attr_accessible :description, :name, :logo, :photo

  translates :name, :description

  has_attached_file :logo, :url  => "/assets/projects/:id/:style/:basename.:extension",
  :ProjectImageth => ":rails_root/public/assets//projects/:id/:style/:basename.:extension"

  #Todo validation on presence
  validates_attachment :logo,# :presence => true,
  :content_type => {:content_type => ["image/jpeg", "image/jpg", "image/png"]},
  :size => {:in => 0..900.kilobytes}

  has_attached_file :photo, :url  => "/assets/projects/:id/:style/:basename.:extension",
  :ProjectImageth => ":rails_root/public/assets//projects/:id/:style/:basename.:extension"

  #Todo validation on presence
  validates_attachment :photo,# :presence => true,
  :content_type => {:content_type => ["image/jpeg", "image/jpg", "image/png"]},
  :size => {:in => 0..1500.kilobytes}
end

app/models/project_image.rb
class ProjectImage < ActiveRecord::Base 
  belongs_to :project

  attr_accessible :description, :name, :event_image, :project_id

  translates :name, :description

 has_attached_file :event_image, :styles => { :thumb => "312x260" },
 :default_style => :thumb,
 :url  => "/assets/products/:id/:style/:basename.:extension",
 :ProjectImageth => ":rails_root/public/assets//products/:id/:style/:basename.:extension"
 
 validates_attachment :event_image, :presence => true,
 :content_type => {:content_type => ["image/jpeg", "image/jpg", "image/png"]},
 :size => {:in => 0..5000.kilobytes}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale

  private
  def set_locale
  	I18n.locale = params[:locale] if params[:locale].present?
  	#request.subdomain
  end

  def default_url_options(options = {})
  	{locale: I18n.locale}
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      ContactForm.new_message(@message).deliver
      redirect_to root_path, :notice => "Message was successfully sent."
    else
      redirect_to root_path(:anchor => (t 'menu.items')[3] ), :notice => "Please fill all fields."
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/project_images_controller.rb
class ProjectImagesController < ApplicationController
  def index
    @project_images = ProjectImage.all
  end

  # GET /project_images/1
  # GET /project_images/1.json
  def show
    @project_image = ProjectImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project_image }
    end
  end

  # GET /project_images/new
  # GET /project_images/new.json
  def new
    @project_image = ProjectImage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project_image }
    end
  end

  # GET /project_images/1/edit
  def edit
    @project_image = ProjectImage.find(params[:id])
  end

  # POST /project_images
  # POST /project_images.json
  def create
    @project_image = ProjectImage.new(params[:project_image])

    respond_to do |format|
      if @project_image.save
        format.html { redirect_to @project_image, notice: 'Project image was successfully created.' }
        format.json { render json: @project_image, status: :created, location: @project_image }
      else
        format.html { render action: "new" }
        format.json { render json: @project_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /project_images/1
  # PUT /project_images/1.json
  def update
    @project_image = ProjectImage.find(params[:id])

    respond_to do |format|
      if @project_image.update_attributes(params[:project_image])
        format.html { redirect_to @project_image, notice: 'Project image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_images/1
  # DELETE /project_images/1.json
  def destroy
    @project_image = ProjectImage.find(params[:id])
    @project_image.destroy

    respond_to do |format|
      format.html { redirect_to project_images_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_images_helper.rb
module ProjectImagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/contact/_new.html.erb
<%= notice %>
<%= form_for message, :url => contact_path do |form| %>
  <% translated_name = t 'message.names'  %>
    <div id="message">
      <div class="leftside">
        <ul>
          <li>
            <%= form.label :name, "#{translated_name[0]}" %>
            <%= form.text_field :name %>
          </li>
          <li>
            <%= form.label :email, "#{translated_name[1]}"  %>
            <%= form.text_field :email %>
          </li>
          <li>
            <%= form.label :subject , "#{translated_name[2]}" %>
            <%= form.text_field :subject %>
          </li>
        </ul>
      </div>
    
    <div class="rightside">
      <ul>
        <li>
          <%= form.label :body, "#{translated_name[3]}" %>
          <%= form.text_area :body, :size => "5x9" %>
        </li>
        <li>
          <%= form.submit "#{translated_name[4]}"  %>
        </li>
      </ul>
    </div>  
  </div>
<% end %>

app/views/contact_form/new_message.text.erb
Name: <%= @message.name %>

Email: <%= @message.email %>

Subject: <%= @message.subject %>

Body: <%= @message.body %>

app/views/home/_about_part.html.erb
<div id="AboutWrapper" class="ContentBorder">
  <div id="SocialWrapper">
    <ul>
      <li>
        <%= image_tag '/assets/fb_logo.png' %> 
      </li>
      <li>
        <%= image_tag '/assets/tw_logo.png' %> 
      </li>
      <li>
        <%= image_tag '/assets/vk_logo.png' %> 
      </li>
    </ul> 
  </div>
    <div class="newsAllRight">
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
    </div>
</div>

app/views/home/_anim_circles.html.erb
<ul class="ch-grid">
<% for i in 1..3 do %>
<li>
  <div class="ch-item">       
    <div class="ch-info">       
        <% case i %>
        <% when 1 %>
          <div class="ch-info-front ch-img-1"></div>
          <div class="ch-info-back">
            <h3>Veni</h3>
            <p>by Julius Caesar <a href="http://en.wikipedia.org/wiki/Veni,_vidi,_vici">View on Wiki</a></p>
        <% when 2 %>
          <div class="ch-info-front ch-img-2"></div>
          <div class="ch-info-back">
            <h3>Vidi</h3>
            <p>by Julius Caesar <a href="http://en.wikipedia.org/wiki/Veni,_vidi,_vici">View on Wiki</a></p>
        <% when 3 %>
          <div class="ch-info-front ch-img-3"></div>
          <div class="ch-info-back">
            <h3>Vici</h3>
            <p>by Julius Caesar <a href="http://en.wikipedia.org/wiki/Veni,_vidi,_vici">View on Wiki</a></p>
        <% end %> 
      </div>  
    </div>
  </div>
</li>
<% end %>
</ul>           

app/views/home/_clients_part.html.erb
<div id="ClientsWrapper" class="ContentBorder">
  <div id="SocialWrapper">
    <ul>
      <li>
        <%= image_tag '/assets/fb_logo.png' %> 
      </li>
      <li>
        <%= image_tag '/assets/tw_logo.png' %> 
      </li>
      <li>
        <%= image_tag '/assets/vk_logo.png' %> 
      </li>
    </ul> 
  </div>
    <div class="newsAllRight">
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
      <div class="newsEvent">
        <h5> Title </h5>
        <p> Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games, 
          giveaways and photo ops for consumers in New York’s Times Square.
          Charlie the Tuna on Feb. 11 celebrated his 50th birthday as the spokes-tuna for StarKist with games,
        </p>
        
      </div>
    </div>
</div>

app/views/home/_home_images.html.erb
<% div_counter = 0 %>
<% ProjectImage.all.each do |project_image| %>
  <% div_counter += 1 %>
  <% div_counter = 1 if div_counter > 3 %>
  <% case div_counter %>
  <% when 1 %>
    <div class="portfolio-image-holder portfolio-image-left"> <%= image_tag project_image.event_image.url(:thumb) %>
      <div class="portfolio-text-bg">
        <p class="portfolio-image-title"><%= project_image.name %></p>
        <p class="portfolio-image-content"><%= project_image.description %></p>        
      </div>
    </div>
  <% when 2 %>
    <div class="portfolio-image-holder portfolio-image-center"> <%= image_tag project_image.event_image.url(:thumb) %>
      <div class="portfolio-text-bg">
        <p class="portfolio-image-title"><%= project_image.name %></p>
        <p class="portfolio-image-content"><%= project_image.description %></p>
      </div>
    </div>
  <% when 3 %>
    <div class="portfolio-image-holder portfolio-image-right"> <%= image_tag project_image.event_image.url(:thumb) %>
      <div class="portfolio-text-bg">
        <p class="portfolio-image-title"><%= project_image.name %></p>
        <p class="portfolio-image-content"><%= project_image.description %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/home/index.html.erb
<% content_for :title do %>
  <%= t 'post_title' %>
<% end %>

<!--Center Part-->
<div id="main">
  <!--Content Area-->
  <div id="content-body">
    <!--Head Line-->
    <div id="static-content">
      <h2><%= t 'pre_portfolio' %></h2>
      <%= render 'anim_circles'%> 
    </div>
    <h2 class="title"><a name="Portfolio"><%= (t 'menu.items')[0] %></a></h2>
    <div class="underline-title"> <%= image_tag '/assets/grey_line.jpg' %> </div>
    <div id="PortfolioWrapper" style="clear:both">
      <%= render 'home_images'%>
		  <% link_to 'New Project image', new_project_image_path %>
		</div>

    <h2 class="title" ><a name="Clients"><%= (t 'menu.items')[1] %></a></h2>
    <div class="underline-title"> <%= image_tag '/assets/grey_line.jpg' %> </div>
    <%= render 'clients_part'%>

    <h2 class="title"><a name="About"><%= (t 'menu.items')[2] %></a></h2>
    <div class="underline-title"> <%= image_tag '/assets/grey_line.jpg' %> </div>
    <%= render 'about_part'%>
    
    <h2 class="title"><a name="Services"><%= (t 'menu.items')[3] %></a></h2>
    <div class="underline-title"> <%= image_tag '/assets/grey_line.jpg' %> </div>
    <div id="ServicesWrapper" class="ContentBorder">
      <div class="left">
       <!-- Longer page -->
       <% for i in 1..12 do %>
          <ul>Lorem Ipsum</ul>
        <% end %>
      </div>
      <div class="right">
       <!-- Longer page -->
       <% for i in 1..12 do %>
          <ul>Lorem Ipsum</ul>
        <% end %>
      </div>
    </div>
    
    <div id="ContactsWrapper">
    <h2 id="ContactsTitle"><a name="Contacts"><%= (t 'menu.items')[4] %></a></h2>
    <div class="underline-title"> <%= image_tag '/assets/grey_line.jpg' %> </div>
    <!-- Here will be contacts :) -->
    <div id="sendMessage"><%= t 'send_us_message' %></div>
       <%= render :partial => '/contact/new', :locals => { :message => Message.new } %>
    </div>
  </div>
</div>

app/views/layouts/_menu.html.erb
<div id="main-menu">
	<ul>
		<li> <%= link_to (t 'menu.items')[0], root_path(anchor: "Portfolio") %></li> 
		<li> <%= link_to (t 'menu.items')[1], root_path(anchor: "Clients") %></li> 
		<li> <%= link_to (t 'menu.items')[2], root_path(anchor: "About") %></li> 
		<li> <%= link_to (t 'menu.items')[3], root_path(anchor: "Services") %></li> 
		<li class="last"> <%= link_to (t 'menu.items')[4], root_path(anchor: "Contacts") %></li> 
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t 'pre_title'%> | <%= yield :title %></title>
  <meta name="description" content="Home" />
  <meta name="keywords" content="" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!--Page Wrapper-->
  <div id="pageWrapper">
    <!--Header Wrapper-->
    <div id="headerWrapper">
      <div id="locales">
        <div class="flag"> <%= link_to_unless_current (image_tag '/assets/uk_flag.jpg'), locale: "en" %> </div>
        <div class="flag"> <%= link_to_unless_current (image_tag '/assets/ru_flag.jpg'), locale: "ru" %> </div>
        <div class="flag"> <%= link_to_unless_current (image_tag '/assets/ua_flag.jpg'), locale: "uk" %> </div>
      </div>
      <!--Logo Section-->
      <div id="logo"> 
        <p class="logoText1">NATIONAL</p> <%= link_to (image_tag '/assets/logo.jpg'), root_path %>  <p class="logoText">SERVICE</p>
      </div>
      <!--Main Menu-->
        <%=  render '/layouts/menu' %>
    </div>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>      
  </div>
</body>
</html>

app/views/project_images/_form.html.erb
<%= form_for(@project_image) do |f| %>
  <% if @project_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_image.errors.count, "error") %> prohibited this project_image from being saved:</h2>

      <ul>
      <% @project_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="file_field">
    <%= f.file_field :event_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/project_images/edit.html.erb
<h1>Editing project_image</h1>

<%= render 'form' %>


<%= link_to 'Show', @project_image %> |
<%= link_to 'Back', project_images_path %>

app/views/project_images/new.html.erb
<h1>New project_image</h1>

<%= render 'form' %>


<%= link_to 'Back', project_images_path %>

app/views/project_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project_image.name %>
</p>

<p>
  <b>Description:</b>
  <%= @project_image.description %>
</p>

<%= @project_image.project %>

<%= image_tag @project_image.event_image.url %>

<%= link_to 'Edit', edit_project_image_path(@project_image) %> |
<%= link_to 'Back', project_images_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td><%= project.description %></td>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% content_for :title do %>
	<%= @project.name %>
<% end %>

<div id="leftContent"> 
  <div id="clientLogo"> 
  	<%= image_tag @project.logo.url %>
  </div>
  <div id="clientDescription"> 
  	<%= @project.description %>
  </div>
</div>
<div id="rightContent"> 
  <div id="clientPicture"> 
  	<%= image_tag @project.photo.url %>
  </div>
</div>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>